# Generated by Django 5.2.6 on 2025-10-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_discordlinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
