# Generated by Django 5.2.6 on 2025-10-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_activities_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='last_deadline_status_notified',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
